// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPasteServices():Promise<Array<Record<string, string>>>;

export function GetSystemLocale():Promise<string>;

export function RunDiagnostic(arg1:string):Promise<void>;

export function SetLocale(arg1:string):Promise<void>;

export function SkipStep():Promise<void>;

export function StopDiagnostic():Promise<void>;

export function UploadPaste(arg1:string,arg2:string):Promise<main.PasteResult>;
