// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPasteServices() {
  return window['go']['main']['App']['GetPasteServices']();
}

export function GetSystemLocale() {
  return window['go']['main']['App']['GetSystemLocale']();
}

export function RunDiagnostic(arg1) {
  return window['go']['main']['App']['RunDiagnostic'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}

export function SkipStep() {
  return window['go']['main']['App']['SkipStep']();
}

export function StopDiagnostic() {
  return window['go']['main']['App']['StopDiagnostic']();
}

export function UploadPaste(arg1, arg2) {
  return window['go']['main']['App']['UploadPaste'](arg1, arg2);
}
